### ISSUE TITLE
change wifi password for final image and publish the password to the documentation 

### ISSUE THREAD

**Issue by lampep** [Nature40/BatRackOS#1]

**Comment by JannisGottwald** [comment]
not really:
Nature40RadioTracking!



Zitat von Jonas Höchst <notifications@github.com>:

**Comment by jonashoechst** [comment]
The password has been changed to "BirdsAndBats" for >= v.1.2, as used in [tRackIT-OS](https://github.com/Nature40/tRackIT-OS)

https://github.com/Nature40/BatRackOS/blob/9eb60409907ab6515d26bbe30c3a3116082b41b6/etc/hostapd/hostapd.conf.sh#L12
